# Generated by Django 5.1.2 on 2024-10-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_alter_visitpage_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitpage',
            table=None,
        ),
    ]
